import { GoogleGenerativeAI, GenerativeModel } from '@google/generative-ai';
import { env } from '../config/env';
import { AppError } from '../middleware/errorHandler';

let geminiModel: GenerativeModel | null = null;

function initializeGemini() {
  if (!geminiModel) {
    if (!env.geminiApiKey) {
      throw new AppError(500, 'Gemini API key is not configured.');
    }
    const genAI = new GoogleGenerativeAI(env.geminiApiKey);
    geminiModel = genAI.getGenerativeModel({ model: 'gemini-pro' });
  }
}

export async function generateMcqQuestion(topic: string = 'Loksewa General Knowledge') {
  initializeGemini();

  if (!geminiModel) {
    throw new AppError(500, 'Gemini model not initialized.');
  }

  const prompt = `Generate a multiple-choice question about ${topic} with exactly four options (A, B, C, D). 
  Include the correct answer and a brief explanation. 
  The output should be in a JSON format like this:
  {
    "question": "What is the capital of Nepal?",
    "options": {
      "A": "Kathmandu",
      "B": "Pokhara",
      "C": "Bhaktapur",
      "D": "Lalitpur"
    },
    "correctAnswer": "A",
    "explanation": "Kathmandu is the capital city of Nepal, located in the Kathmandu Valley."
  }`;

  try {
    const result = await geminiModel.generateContent(prompt);
    const response = result.response;
    const text = response.text();

    // The Gemini API can sometimes return markdown or extra text.
    // Try to extract the JSON part.
    const jsonMatch = text.match(/```json\n([\s\S]*?)\n```/);
    let jsonString = text;
    if (jsonMatch && jsonMatch[1]) {
      jsonString = jsonMatch[1];
    } else {
      // Fallback: if no markdown, assume the whole text is JSON
      jsonString = text;
    }

    const mcq = JSON.parse(jsonString);

    // Basic validation
    if (!mcq.question || !mcq.options || !mcq.correctAnswer || !mcq.explanation) {
      throw new AppError(500, 'Invalid MCQ format generated by AI.');
    }
    if (!['A', 'B', 'C', 'D'].includes(mcq.correctAnswer)) {
      throw new AppError(500, 'Invalid correct answer option generated by AI.');
    }

    return mcq;
  } catch (error) {
    console.error('Error generating MCQ question:', error);
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to generate MCQ question from AI.');
  }
}